import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar.js'
import PeopleWorking from './people working.svg'
import ShrinkForm from '../components/ShrinkForm.js'
import Context from '../components/Context.js'
import Chain from '../components/Chain.js'
import GetStarted from '../components/GetStarted'
import Footer from '../components/Footer'

// import styles from '../styles/Home.module.css' // DELETE THIS IN THE END AND THE CSS-FILE ALSO
import { css } from '@emotion/css'

export default function Home() {
  return (
    <div className={css`
      padding:0;
      margin:0;
      overflow-x:hidden;
      scroll-behavior:smooth;`}>

      <Head>
        <title>TIF - Round 2 Assignment Submission</title>
        <meta name="description" content="Generated by create next app by Moksh Nigam" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;700&display=swap" rel="stylesheet" />
      </Head>

      <main className={css`font-size: 18px;`}>
        <div className={css`
          margin: 0;
          padding: 0;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          max-width: 100vw;
          height: auto;
          // outline: 2px solid black;`}>
          <section>
            <Navbar />
          </section>

          <h1 className={css`
              margin-top: -0.5%;
              text-transform: uppercase;
              text-align: center;
              font-size: 6.1em;
              font-family: 'Poppins', sans-serif;
              font-weight: bold;
              line-height: 1.2;
              color: #35323e;

              @media (max-width: 375px) {
                font-size: 3em;
                margin-top: 0;
              }
              // outline: 2px solid red;`}>
            More Than Just<br />Shorter Links
          </h1>

          <PeopleWorking className={css`
            margin-top: -5%;
            @media (max-width: 375px) {
              margin-top: 0;
              transform: scale(0.94);
            }`} />
        </div>

        <div className={css`
          margin: 0;
          padding: 0;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: space-between;
          width: 100%;
          height: 100%;
          background: #e8edea;
          position: relative;

          @media (max-width: 375px) {
            margin-top: 25%;
          }
          // outline: 2px solid black;`}>
            
            <ShrinkForm />
            <Context />
            <Chain />
            <GetStarted />

          </div>
      </main>

      <Footer />

    </div>
  )
}
